### ISSUE TITLE
Push new release to rubygems

### ISSUE THREAD

**Issue by szymonpk** [Nordstrom/guard-foodcritic#17]
Could you push guard-foodcritic with foodcritic 6.0 support to rubygems? It requires too many steps to install it via Gemfile

```
...
gem "guard-foodcritic", git: "git@github.com:Nordstrom/guard-foodcritic.git",
  ref: 'd157f
...
```

```bash
bundle package --no-install --all; bundle install --local --no-prune
```

**Comment by zuazo** [comment]
I am very interested in this. ChefDK already comes with foodcritic `6`. It would be nice to update this gem accordingly.

**Comment by spuder** [comment]
+1

**Comment by dougireton** [comment]
Working on this now

**Comment by dougireton** [comment]
@zuazo @szymonpk I'm all ready to push, but I don't have rights. I'm waiting on the gem owner to grant me push rights.

```
guard-foodcritic 2.1.0 built to pkg/guard-foodcritic-2.1.0.gem.
Tagged v2.1.0.
Pushed git commits and tags.

rake aborted!
Pushing gem to https://rubygems.org...
You do not have permission to push to this gem.
```

**Comment by dougireton** [comment]
Ok. Thanks for your patience. `guard-foodcritic` v2.1 with support for foodcritic 6.0 has been released.

**Comment by zuazo** [comment]
Thanks @dougireton :wink:
